name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: oonishi-hikaru-portfolio/package-lock.json
        
    - name: Install dependencies
      run: |
        cd oonishi-hikaru-portfolio
        npm ci
        
    - name: Run type checking
      run: |
        cd oonishi-hikaru-portfolio
        npm run type-check
        
    - name: Run linting
      run: |
        cd oonishi-hikaru-portfolio
        npm run lint
        
    - name: Check for security vulnerabilities
      run: |
        cd oonishi-hikaru-portfolio
        npm run audit
        
    - name: Build project
      run: |
        cd oonishi-hikaru-portfolio
        npm run build
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: oonishi-hikaru-portfolio/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 